name: Deploy Docs

on:
  push:
    branches:
      - develop
      - main

jobs:
  Book-and-Docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # - name: Book
      #   run: docker-compose run book

      - name: Docs
        run: docker-compose run docs

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.TOKEN }}
          publish_dir: ./docs

