name: Run Tests

on:
  push:
    branches:
      - devel
      - main
  pull_request:
    branches:
      - devel
      - main

jobs:
  Tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: postgres tests
        run: docker-compose run tests-postgres
      - name: sqlite tests
        run: docker-compose run tests-sqlite

