name: Run Tests

on:
  push:
    branches:
      - devel
      - main
  pull_request:
    branches:
      - devel
      - main

jobs:
  Tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: postgres tests
        run: docker-compose run tests-postgres
      - name: sqlite tests
        run: docker-compose run tests-sqlite

  Book:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Book
        run: |
          sudo apt update -y
          sudo apt install -y libpcre++-dev
          nimble nimidocs

  Docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Docs
        run: docker-compose run docs

