name: Run Tests

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  Tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: postgres tests
        run: docker-compose run tests-postgres
      - name: sqlite tests
        run: docker-compose run tests-sqlite

  Book:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Book
        run: docker-compose run book

  Docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Docs
        run: docker-compose run docs

